# Generated by Django 5.1.7 on 2025-04-07 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kunde',
            fields=[
                ('kunden_nr', models.AutoField(primary_key=True, serialize=False)),
                ('firma', models.CharField(max_length=60)),
                ('anschrift', models.CharField(max_length=60)),
                ('plz', models.CharField(blank=True, max_length=10)),
                ('stadt', models.CharField(max_length=50)),
                ('telefon_nr', models.CharField(blank=True, max_length=20)),
                ('fax_nr', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_count', models.IntegerField(default=0)),
                ('last_attempt_time', models.DateTimeField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('lock_time', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vermerk',
            fields=[
                ('gespraechs_id', models.AutoField(primary_key=True, serialize=False)),
                ('datum', models.DateField(auto_now_add=True)),
                ('uhrzeit', models.TimeField()),
                ('kontaktart', models.CharField(choices=[('Eingehender Anruf', 'Anruf von'), ('Ausgehender Anruf', 'Anruf bei'), ('Im Büro', 'Besuch von'), ('Beim Kunden', 'Besuch bei')], default='Anruf', max_length=18)),
                ('anrede', models.CharField(choices=[('Herr', 'Herr'), ('Frau', 'Frau'), ('Divers', 'Divers')], default='Herr', max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('betreff', models.CharField(max_length=40)),
                ('wunsch', models.CharField(choices=[('wünscht Rückruf', 'wünscht Rückruf'), ('wünscht Termin', 'wünscht Termin'), ('ruft wieder zurück', 'ruft wieder an')], default='wünscht Rückruf', max_length=20)),
                ('gespraechsinhalt', models.TextField()),
                ('aufgenommen', models.CharField(default='', max_length=40)),
                ('verfuegung', models.CharField(default='', max_length=40)),
                ('firmen_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vermerke', to='verwaltung.kunde')),
            ],
        ),
    ]
