# Generated by Django 5.1.7 on 2025-04-08 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verwaltung', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vermerk',
            name='verfuegung',
            field=models.CharField(default='', max_length=100),
        ),
    ]
